### PR TITLE
Link modules.4th to modules.fs

### PR DESCRIPTION
**Pull request by iru-**

### CODE REVIEW

**Comment by mynenik** [comment]
Let's make a link, modules.4th, which points to modules.fs. The name modules.fs was retained because it was developed by David Williams and me, and changes will have to be made to the literate programming source. Changing the name make break existing programs, so it is better to retain the file and simply make a link.

**Comment by iru-** [comment]
> Let's make a link, modules.4th, which points to modules.fs. The name modules.fs was retained because it was developed by David Williams and me, and changes will have to be made to the literate programming source. Changing the name make break existing programs, so it is better to retain the file and simply make a link.

Should we make a link or fix the inclusions to name `modules.fs` instead of `modules`? I prefer the latter, but either way seems ok.

**Comment by mynenik** [comment]
The original source from which modules.fs is derived is the file modular-forth.lyx -- this is a "literate program" which includes both the code and documentation in a more comprehensible format. The modules framework was written to be portable to all Forth-94/2012 standard systems, and some systems use the .fs extension. It was decided at that time to stick with the .fs file extension. Changing the file extension by itself creates a mismatch between the true source (modular-forth.lyx) and the extracted code, which I would rather not do. Using a link is a much simpler thing to do -- no existing files would have to be modified.

**Comment by iru-** [comment]
Done!

**Pull request merged**
